export default {
    SET_FORM: 'SET_FORM',
    SET_NOTES: 'SET_NOTES',
    SET_LOADING: 'SET_LOADING',
    SET_TEMPLATES: 'SET_TEMPLATES',
    SET_FORWARDING_REQUEST: 'SET_FORWARDING_REQUEST',
    CLEAR_FORM: 'CLEAR_FORM',
    ADD_TO_HISTORY: 'ADD_TO_HISTORY',
    SAVE_TEMPLATE: 'SAVE_TEMPLATE',
    DELETE_TEMPLATE: 'DELETE_TEMPLATE',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    FETCHED_AUTH: 'FETCHED_AUTH',
    FETCHED_LOGIN: 'FETCHED_LOGIN',
    FETCHED_LOGOUT: 'FETCHED_LOGOUT',
    FETCHED_FAILURE: 'FETCHED_FAILURE',
    FETCHED_FORWARDING_NOTES: 'FETCHED_FORWARDING_NOTES',
    FETCHED_FORWARDING_REQUEST: 'FETCHED_FORWARDING_REQUEST',
    FETCHED_FORWARDING_REQUEST_CREATE: 'FETCHED_FORWARDING_REQUEST_CREATE',
    FETCHED_FORWARDING_REQUEST_TEMPLATES: 'FETCHED_FORWARDING_REQUEST_TEMPLATES',
    FETCHED_FORWARDING_REQUEST_SAVE_TEMPLATE: 'FETCHED_FORWARDING_REQUEST_SAVE_TEMPLATE',
    FETCHED_FORWARDING_REQUEST_DELETE_TEMPLATE: 'FETCHED_FORWARDING_REQUEST_DELETE_TEMPLATE'
}