export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    FETCHED_FAILURE: 'FETCHED_FAILURE',

    CLEAR_FORM: 'CLEAR_FORM',
    SET_FORM: 'SET_FORM',
    SET_NOTES: 'SET_NOTES',
    SET_LOADING: 'SET_LOADING',
    SET_TEMPLATES: 'SET_TEMPLATES',
    SET_FORWARDING_REQUEST: 'SET_FORWARDING_REQUEST'
}