export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_PENDING: 'LOGIN_PENDING',
    FETCHED_LOGIN: 'FETCHED_LOGIN',
    FETCHED_FAILURE: 'FETCHED_FAILURE',
    SET_FORM: 'SET_FORM',
    CLEAR_FORM: 'CLEAR_FORM',
    ADD_TO_HISTORY: 'ADD_TO_HISTORY',
    SAVE_TEMPLATE: 'SAVE_TEMPLATE',
    DELETE_TEMPLATE: 'DELETE_TEMPLATE'
}